name: App CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: go --version
      - run: go mod download
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: docker-compose down --volumes
        if: always()
